version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Algolia
  ALGOLIA_APP_ID: app_id
  ALGOLIA_API_KEY: api_key
  ALGOLIA_INDEX_NAME: index_name
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # DuckDB
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  # Google
  # GOOGLE_SERVICE_ACC_KEY:
  #   type: service_account
  #   project_id: crested-talon-417601
  #   private_key_id: 541f697481af31a47afd5135ae201130fa8067df
  #   private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDc5k/lh2ES2hLn\nPnoDdjbjOAt/XaYKtp0Kp2oTxmu90w0GRAv8G5Nd3KxVgPKcD7ETa/DFmxyncTk3\na8TswFTCaOOs8EpZGIjQsy/1TFeOSr/fvgK36vFIFhBq9MNMsE3H5CGgk2ETgk9U\nQ3JCNaYEn5ntlwr2QNd067J4g7n1BqkyfDSyx5lc7YNwHaPMKf1C2hAs4rDjyppq\nl85+98h4ySphmVAv98SwMOJzEr/FPol7qCjK9Sn5i1EG+aJ9DkKgl4b03R3cqFgt\nfDYi2xJ0ffpgN4T6WAqm/m4wld2y5dCk3UsRpNh/eE1x4kwLxRxIRSD7L1BBhrxW\nm9xpFJV1AgMBAAECggEAK59Xu84GP4DNJtlRowlfQXO54YcO2SLC1G3HJuySLkRV\nWB1r+HdBnNGNPr1eK691mo5AV+WPvQlA8U7Y7p/0nQe1nls9c2bC7ePU3q4axEDC\nr16IjuVYjJG+4EBBqQ1P7t+APIOeMgoTvGItWCHcDSGvdhnT0llvsukwr1fkCxzN\ntB9e5oTgLjjruIHbB3wM9VbGDkgwjM+gggSGA4UEha3bgxHF4FkVGaSBR+OOWl4j\n7tRYu88rSGkIncvkkRZrcTzQZQvobAfkx6loyWGYDwFd0qXE9G015+0jWSbIXLnJ\nM/X63kX0FmLicvVkBTytomdFh4lcOX5aT0Qx+ELrwQKBgQDvk451QZVV508SgD4X\nggHk7x2fwK5rcRrbYIgcn1OW/3Rffhtf5uIGX8rbzSHDmwunePgXuEH42nkr/spa\n4cuhfQ4UogUpD0fj/ZSumHzqGvD+AZm64ecNlJUIF2uP6P6XI8QOW3NYdaboooPO\nqIEHHrCHVSUP5wQ4IXmSPVNm3QKBgQDsCv0JqTgk76SnRAcyid5D5V2ppZAdoTT2\nRg4cm9AvNIbklcS7+7lW7S/jWhYMi24js8wfyWUn31TnTNpLlTAat4escQ/yHQHO\nwFabs3ba1nTgcG1LnV0LDdduwadJfHqrmoNS3GSlQjZ+2CejgyNtcQKKt9Mv4RXY\njzRiX4/jeQKBgQCG2O8eYMPFjmSbbUOFx895JH3wJWwHXapYQIVcVvGd1DuUZE7U\nNAiUveZYwaV3jBWLNjOuZi/7+jyp3sfXT7BmPRVn16o/6jH0yg6eF4Z33qI21n/J\nCM4cfr1DyKrqXaKvP5pi2maaK96+onq+H2pAr618/xfVU5q0XWMoRQxkoQKBgQC+\nn0kmSjB7M8UnB7tARzLmZg8z9+7g3tVkpcKzu+luld7yLzlIDsvotXfdBV2VF+0E\njCkm6n/0qVlpyhjovTyx9tFso4obHu3cyFupNk+f/103+9NoI1eGm9EFMwMkR5DR\nkODJRA9LnqNf4LRySm+L7J3+5OF6Yy4/S7ckUsRjEQKBgQCrRj587ECdZwi45qCh\nEgfF9w43FRTdrE8tyGUolnvxxvJ2uJYT+qP7nK/lYVFXREpLXv0xngzlsCGVES24\nE+l3r0kLQdhrg1QaLvZ43yYCMdhF6SQL38Q3ZjgPKO91Z4Ow/c/E/JZJewXlKYGx\nxqFcoRCZ+vG4cWGeXqvIQNnXhQ==\n-----END PRIVATE KEY-----\n"
  #   client_email: "gcs-bq@crested-talon-417601.iam.gserviceaccount.com"
  #   auth_uri: "https://accounts.google.com/o/oauth2/auth"
  #   token_uri: "https://oauth2.googleapis.com/token"
  #   auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
  #   client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/gcs-bq%40crested-talon-417601.iam.gserviceaccount.com"
  # GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/path/to/your/service/account/key.json"
  # GOOGLE_LOCATION: US # Optional
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_COLLECTION: collectionn_name
