bgg:
  outputs:
    dev:
      dataset: bgg_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('path_to_keyfile') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 1
      type: bigquery
    prod:
      dataset: bgg_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('path_to_keyfile') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 1
      type: bigquery
  target: prod